import jsPDF from "jspdf";
import {
  type CalculatorResult,
  formatCurrency,
  formatCurrencyDecimal,
} from "./calculator";

export function generateReportPdf(result: CalculatorResult): string {
  const doc = new jsPDF();
  const margin = 20;
  let y = 20;

  const addLine = (text: string, fontSize = 10, bold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, 170);
    for (const line of lines as string[]) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += fontSize * 0.5 + 2;
    }
  };

  const addGap = (size = 6) => {
    y += size;
  };

  addLine("SurchargeSwap Report", 18, true);
  addLine("Your Surcharge Ban Impact Analysis", 11);
  addGap(8);

  addLine("YOUR INPUTS", 12, true);
  addGap(2);
  addLine(
    `Monthly card revenue: ${formatCurrency(result.inputs.monthlyCardRevenue)}`
  );
  addLine(`Visa/Mastercard: ${result.inputs.visaMastercardPct}%`);
  addLine(`eftpos: ${result.inputs.eftposPct}%`);
  addLine(`Amex: ${result.inputs.amexPct}%`);
  addLine(`BNPL: ${result.inputs.bnplPct}%`);
  addLine(`Surcharge rate: ${result.inputs.currentSurchargePct}%`);
  addLine(`MSF rate: ${result.inputs.currentMsfPct}%`);
  addGap(8);

  addLine("MONTHLY IMPACT", 12, true);
  addGap(2);
  addLine(
    `Revenue you'll stop collecting: -${formatCurrency(result.surchargeRevenueLost)}`
  );
  addLine(
    `Net monthly hit: -${formatCurrency(result.netMonthlyImpact)}`
  );
  addLine(
    `Annual equivalent: -${formatCurrency(result.annualImpact)}`
  );
  addGap(8);

  addLine("AMEX (EXEMPT)", 12, true);
  addGap(2);
  addLine(
    `Your Amex revenue: ${formatCurrency(result.amexRevenue)}/mo`
  );
  addLine(
    `Recoverable surcharge: ${formatCurrency(result.amexSurchargeRecovery)}/mo`
  );
  addGap(8);

  addLine("BNPL COST", 12, true);
  addGap(2);
  addLine(
    `BNPL volume: ${formatCurrency(result.bnplRevenue)}/mo at ~4.5% MSF = ${formatCurrency(result.bnplMsfCost)}/mo`
  );
  addGap(8);

  addLine("INTERCHANGE SAVING (COST-PLUS)", 12, true);
  addGap(2);
  addLine(
    `Estimated monthly saving: ${formatCurrency(result.interchangeSaving)}`
  );
  addGap(8);

  addLine("PROCESSOR COMPARISON", 12, true);
  addGap(2);
  for (const comp of result.processorComparison) {
    addLine(
      `#${comp.rank} ${comp.processor.name} (${(comp.processor.rate * 100).toFixed(1)}%) — Monthly cost: ${formatCurrency(comp.monthlyCost)} — Saving: ${formatCurrency(comp.monthlySaving)}/mo (${formatCurrency(comp.annualSaving)}/yr)`,
      9
    );
    addGap(2);
  }
  addGap(4);

  addLine("REPRICING ANALYSIS", 12, true);
  addGap(2);
  addLine(
    `Required price increase: ${result.requiredPriceIncreasePct.toFixed(1)}%`
  );
  addLine(
    `$20.00 item becomes ${formatCurrencyDecimal(20 * (1 + result.requiredPriceIncreasePct / 100))}`
  );
  addLine(
    `$5.00 item becomes ${formatCurrencyDecimal(5 * (1 + result.requiredPriceIncreasePct / 100))}`
  );
  addLine(
    `Annual revenue impact: +${formatCurrency(result.annualRepriceRevenue)}/yr`
  );
  addGap(10);

  addLine(
    "Disclaimer: This report is for informational purposes only and does not constitute financial advice.",
    8
  );
  addLine(
    "Indicative rates only. Verify with your processor before making decisions.",
    8
  );
  addLine("Generated by SurchargeSwap — surchargeswap.com.au", 8);

  return doc.output("datauristring").split(",")[1];
}
